[platformio]
default_envs = wokwi

[env:wokwi]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
build_flags =
  -D ROBOFUSION_WOKWI=1
lib_deps =
  beegee-tokyo/DHT sensor library for ESPx@^1.19.0

